### PR TITLE
OneWayShootingMover as a proper class

### PR DESCRIPTION
**Pull request by dwhswenson**
Converting OneWayShootingMover from a MixedMover to a true subclass.

To-do:

- [x] Create OneWayShootingMover class
- [x] Add docs
- [x] Add tests

### CODE REVIEW

**Comment by dwhswenson** [comment]
This is ready to merge.

**Comment by jhprinz** [comment]
Good work. Merging.

What is `CalvinDynamics` ? Does it use the HobbesIntegrator?

**Comment by dwhswenson** [comment]
> What is `CalvinDynamics` ? Does it use the HobbesIntegrator?

Ha! Just a little religion joke hidden in the tests. In `CalvinDynamics`, paths are predestined: whether they are the elect who pass a test is beyond any natural law and depends solely on the grace of the Programmer, who decided their fate before they were instantiated. ;-)

**Comment by jchodera** [comment]
Wouldn't that be ‘CalvinistDynamics‘?

**Comment by dwhswenson** [comment]
Hmmmm, good point @jchodera. This will be fixed in #124.

(Good thing I'm fixing all the really important stuff, right?)

**Comment by jhprinz** [comment]
Okay, than the HobbesIntegrator induces the non-deterministic part ;)

The describtion of CalvinBall
> Calvinball is a game invented by Calvin in which one makes the rules up as one goes along. Rules cannot be used twice (except for the rule that rules cannot be used twice). No Calvinball game is like another. The game may involve wickets, mallets, volleyballs, and additional equipment as well as masks.

**Pull request merged**
